version: '3.7'
services:
  jupyterlab:
    image: 'docker-jupterlab:latest'
    build: .
    container_name: docker-jupterlab
    environment:
      - NB_UID=100
      - GEN_CERT=yes
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '80:8888'
